" Pathogen Init
execute pathogen#infect()
execute pathogen#helptags()

syntax on
colorscheme dracula 
filetype plugin indent on

" Airline extensions
let g:airline_extensions = ['tmuxline', 'tabline']

" - set airline theme
let g:airline_theme='dracula'

" - convenience var for airline fonts
let g:airline_powerline_fonts = 1

" - set tmux status line with airline's tmuxline
let g:tmuxline_powerline_separators = 1

" - enable smarter vim airline buffer tab line
let g:airline#extensions#tabline#enabled = 1

" - map relative number toggle
nmap <silent> <C-l> :exec &rnu? "se rnu!" : "se rnu"<CR>

" - easy buffer navigation
let mapleader = ';'
noremap <leader>n :bn<cr>
noremap <leader>p :bp<cr>
noremap <leader>d :bd<cr>

" - easier window navigation
map <leader>j <C-W>j<C-W>
map <leader>k <C-W>k<C-W>
map <leader>h <C-W>h<C-W>
map <leader>l <C-W>l<C-W>

" Ale
" - lint only on save
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0

" editorconfigs
set autoindent
set indentexpr=off
set expandtab
set tabstop=4
set softtabstop=4
set number

set sw=4
set textwidth=80
set nohls
set noshowmatch
setlocal spell spelllang=en_us
set nospell

set modeline
set nojoinspaces " pesky 2-spaces after the period thing - substack :p

set nowritebackup
set noswapfile
set nobackup

