" Pathogen Init
execute pathogen#infect()
execute pathogen#helptags()

syntax on
colorscheme dracula 
filetype plugin indent on

" Airline
let g:airline_extensions = ['tmuxline', 'tabline']
" - set airline theme
let g:airline_theme='dracula'

" - convenience var for airline fonts
let g:airline_powerline_fonts = 1

" - set tmux status line with airline's tmuxline
let g:tmuxline_powerline_separators = 1

" - enable smarter vim airline buffer tab line
let g:airline#extensions#tabline#enabled = 1

" - easy buffer navigation
map gn :bn<cr>
map gp :bp<cr>
map gd :bd<cr>

" - map relative number toggle
nmap <silent> <C-l> :exec &rnu? "se rnu!" : "se rnu"<CR>

" - easier window navigation
map <C-J> <C-W>j<C-W>
map <C-K> <C-W>k<C-W>

" Ale
" - lint only on save
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0

" editorconfigs
set autoindent
set indentexpr=off
set expandtab
set tabstop=2
set number

set sw=4
set textwidth=80
set nohls
set noshowmatch
setlocal spell spelllang=en_us
set nospell

set modeline
set nojoinspaces " pesky 2-spaces after the period thing - substack :p

set nowritebackup
set noswapfile
set nobackup

