" Pathogen Init
execute pathogen#infect()
execute pathogen#helptags()

" - Basic setup
set nocompatible

syntax on
colorscheme dracula 
filetype plugin indent on

" - Finding files recursively
set path+=**

" - display found files in tabline
set wildmenu
set wildignore+=**/node_modules/**

" Airline extensions
let g:airline_extensions = ['tmuxline', 'tabline']

" - set airline theme
let g:airline_theme='dracula'

" - convenience var for airline fonts
let g:airline_powerline_fonts = 1

" - set tmux status line with airline's tmuxline
let g:tmuxline_powerline_separators = 1

" - enable smarter vim airline buffer tab line
let g:airline#extensions#tabline#enabled = 1

" - map relative number toggle
nmap <silent> <C-l> :exec &rnu? "se rnu!" : "se rnu"<CR>

" - set leader key
let mapleader = ';'

" - easy buffer navigation
noremap <leader>n :bn<cr>
noremap <leader>p :bp<cr>
noremap <leader>d :bd<cr>

" - easier window navigation
map <leader>j <C-W>j<C-W>
map <leader>k <C-W>k<C-W>
map <leader>h <C-W>h<C-W>
map <leader>l <C-W>l<C-W>

" Ale
" - lint only on save
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0

" - editorconfigs
set autoindent
set indentexpr=off
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2 
set number

" - for indent lines
" https://vi.stackexchange.com/questions/666/how-to-add-indentation-guides-lines
" set cursorcolumn
" set cursorline

set textwidth=80
set nohls
set noshowmatch
setlocal spell spelllang=en_us
set nospell

set modeline
set nojoinspaces " pesky 2-spaces after the period thing - substack :p

set nowritebackup
set noswapfile
set nobackup

