" - Vim Plug
call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'
Plug 'dracula/vim', {'as': 'dracula'}
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'w0rp/ale'
Plug 'ajh17/VimCompletesMe'
Plug 'mattn/emmet-vim'
Plug 'ryanoasis/vim-devicons'
Plug 'mhinz/vim-startify'
Plug 'jiangmiao/auto-pairs'
Plug 'airblade/vim-gitgutter'
Plug 'pangloss/vim-javascript'
Plug 'neovimhaskell/haskell-vim'

" - Initialize plugin system
call plug#end()

" - Basic setup
set nocompatible
syntax on
filetype plugin indent on

" Recent Dracula Theme messed up a ton of things ...
" these settings resolve the issues 
let g:dracula_italic = 0
colorscheme dracula
highlight Normal ctermbg=None

" - Vim Airline
" let g:airline_powerline_fonts=0
" let g:airline#extensions#tabline#enabled=1
" let g:airline_theme='dracula'

" - Vim Lightline
set laststatus=2
let g:lightline = {
  \ 'colorscheme': 'Dracula',
  \ }

" - Finding files recursively
set path+=**

" - display found files in tabline
set wildmenu
set wildignore+=**/node_modules/**

" - map relative number toggle
nmap <silent> <C-l> :exec &rnu? "se rnu!" : "se rnu"<CR>

" - set leader key
let mapleader = ';'

" - easy buffer navigation
noremap <leader>n :bn<cr>
noremap <leader>p :bp<cr>
noremap <leader>d :bd<cr>

" - easier window navigation
map <leader>j <C-W>j<C-W>_
map <leader>k <C-W>k<C-W>_
map <leader>h <C-W>h<C-W>
map <leader>l <C-W>l<C-W>

set winminheight=0
set winheight=999
" - set window height to 0 by default
" - helps with screen real-estate :)

" - GitGutter
set updatetime=1000
nmap <Leader>gs <Plug>GitGutterStageHunk
nmap <Leader>gu <Plug>GitGutterUndoHunk
nmap <Leader>gp <Plug>GitGutterPreviewHunk

" Ale
" - lint only on save
" Write this in your vimrc file
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0

" Tmuxline
" let g:tmuxline_powerline_separators = 0
" let g:tmuxline_preset = {
        " \ 'a': '#S',
        " \ 'win': '#I #W',
        " \ 'cwin': '#I #W',
        " \ 'z': 'up: #(get_uptime)',
        " \ 'options': {
        " \ 'status-justify': 'left'}}

" - editorconfigs
set autoindent
set indentexpr=off
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2 
set number

" - for indent lines
" https://vi.stackexchange.com/questions/666/how-to-add-indentation-guides-lines
" set cursorcolumn
" set cursorline

set textwidth=80
set nohls
set noshowmatch
set noshowmode
setlocal spell spelllang=en_us
set nospell

set modeline
set nojoinspaces " pesky 2-spaces after the period thing - substack :p

set nowritebackup
set noswapfile
set nobackup

