" - Vim Plug
call plug#begin('~/.vim/plugged')

Plug 'airblade/vim-gitgutter'
Plug 'ajh17/VimCompletesMe'
Plug 'dracula/vim', {'as': 'dracula'}
Plug 'itchyny/lightline.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'mattn/emmet-vim'
Plug 'mhinz/vim-startify'
Plug 'neovimhaskell/haskell-vim'
Plug 'pangloss/vim-javascript'
Plug 'ryanoasis/vim-devicons'

Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'

Plug 'w0rp/ale'

" - Initialize plugin system
call plug#end()

" - set leader key
let mapleader = ';'

set encoding=UTF-8

" - Basic setup
set nocompatible
syntax on
filetype plugin indent on

" - Finding files recursively
set path+=**

" - display found files in tabline
set wildmenu
set wildignore+=**/node_modules/**

" - map relative number toggle
nmap <silent> <C-l> :exec &rnu? "se rnu!" : "se rnu"<CR>

" - easy buffer navigation
noremap <leader>n :bn<cr>
noremap <leader>p :bp<cr>
noremap <leader>d :bd<cr>

" - easier window navigation
map <leader>j <C-W>j<C-W>_
map <leader>k <C-W>k<C-W>_
map <leader>h <C-W>h<C-W>
map <leader>l <C-W>l<C-W>

set winminheight=0
set winheight=999
" - set window height to 0 by default
" - helps with screen real-estate :)

" - editorconfigs
set autoindent
set indentexpr=off
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2 
set number

" - for indent lines
" https://vi.stackexchange.com/questions/666/how-to-add-indentation-guides-lines
" set cursorcolumn
" set cursorline

set textwidth=80
set nohls
set noshowmatch
set noshowmode
setlocal spell spelllang=en_us
set nospell

set modeline
set nojoinspaces " pesky 2-spaces after the period thing - substack :p

set nowritebackup
set noswapfile
set nobackup

" Plugin: dracula
" Recent Dracula Theme messed up a ton of things ...
" these settings resolve the issues 
let g:dracula_italic = 0
colorscheme dracula
highlight Normal ctermbg=None

" Plugin: GitGutter
set updatetime=1000
nmap <Leader>gs <Plug>GitGutterStageHunk
nmap <Leader>gu <Plug>GitGutterUndoHunk
nmap <Leader>gp <Plug>GitGutterPreviewHunk

" Plugin: Ale
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0


" Plugin: netrw {{{2
" let g:loaded_netrwPlugin = 1
let g:netrw_banner       = 0
let g:netrw_bufsettings  = 'relativenumber'
let g:netrw_keepdir      = 0
let g:netrw_liststyle    = 1
let g:netrw_sort_options = 'i'

" Plugin: lightline {{{1
set laststatus=2
let g:lightline = {
      \ 'colorscheme': 'Dracula',
      \ 'component_function': {
      \   'filetype': 'MyFiletype',
      \   'fileformat': 'MyFileformat',
      \ }
    \ }

function! MyFiletype()
  return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
endfunction

function! MyFileformat()
  return winwidth(0) > 70 ? (&fileformat . ' ' . WebDevIconsGetFileFormatSymbol()) : ''
endfunction

