
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
" XX                                                                          XX
" XX   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM   XX
" XX   MMMMMMMMMMMMMMMMMMMMMssssssssssssssssssssssssssMMMMMMMMMMMMMMMMMMMMM   XX
" XX   MMMMMMMMMMMMMMMMss'''                          '''ssMMMMMMMMMMMMMMMM   XX
" XX   MMMMMMMMMMMMyy''                                    ''yyMMMMMMMMMMMM   XX
" XX   MMMMMMMMyy''                                            ''yyMMMMMMMM   XX
" XX   MMMMMy''                                                    ''yMMMMM   XX
" XX   MMMy'                                                          'yMMM   XX
" XX   Mh'                                                              'hM   XX
" XX   -                                                                  -   XX
" XX                                                                          XX
" XX   ::                                                                ::   XX
" XX   MMhh.        ..hhhhhh..                      ..hhhhhh..        .hhMM   XX
" XX   MMMMMh   ..hhMMMMMMMMMMhh.                .hhMMMMMMMMMMhh..   hMMMMM   XX
" XX   ---MMM .hMMMMdd:::dMMMMMMMhh..        ..hhMMMMMMMd:::ddMMMMh. MMM---   XX
" XX   MMMMMM MMmm''      'mmMMMMMMMMyy.  .yyMMMMMMMMmm'      ''mmMM MMMMMM   XX
" XX   ---mMM ''             'mmMMMMMMMM  MMMMMMMMmm'             '' MMm---   XX
" XX   yyyym'    .              'mMMMMm'  'mMMMMm'              .    'myyyy   XX
" XX   mm''    .y'     ..yyyyy..  ''''      ''''  ..yyyyy..     'y.    ''mm   XX
" XX           MN    .sMMMMMMMMMss.   .    .   .ssMMMMMMMMMs.    NM           XX
" XX           N`    MMMMMMMMMMMMMN   M    M   NMMMMMMMMMMMMM    `N           XX
" XX            +  .sMNNNNNMMMMMN+   `N    N`   +NMMMMMNNNNNMs.  +            XX
" XX              o+++     ++++Mo    M      M    oM++++     +++o              XX
" XX                                oo      oo                                XX
" XX           oM                 oo          oo                 Mo           XX
" XX         oMMo                M              M                oMMo         XX
" XX       +MMMM                 s              s                 MMMM+       XX
" XX      +MMMMM+            +++NNNN+        +NNNN+++            +MMMMM+      XX
" XX     +MMMMMMM+       ++NNMMMMMMMMN+    +NMMMMMMMMNN++       +MMMMMMM+     XX
" XX     MMMMMMMMMNN+++NNMMMMMMMMMMMMMMNNNNMMMMMMMMMMMMMMNN+++NNMMMMMMMMM     XX
" XX     yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy     XX
" XX   m  yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy  m   XX
" XX   MMm yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy mMM   XX
" XX   MMMm .yyMMMMMMMMMMMMMMMM     MMMMMMMMMM     MMMMMMMMMMMMMMMMyy. mMMM   XX
" XX   MMMMd   ''''hhhhh       odddo          obbbo        hhhh''''   dMMMM   XX
" XX   MMMMMd             'hMMMMMMMMMMddddddMMMMMMMMMMh'             dMMMMM   XX
" XX   MMMMMMd              'hMMMMMMMMMMMMMMMMMMMMMMh'              dMMMMMM   XX
" XX   MMMMMMM-               ''ddMMMMMMMMMMMMMMdd''               -MMMMMMM   XX
" XX   MMMMMMMM                   '::dddddddd::'                   MMMMMMMM   XX
" XX   MMMMMMMM-                                                  -MMMMMMMM   XX
" XX   MMMMMMMMM                                                  MMMMMMMMM   XX
" XX   MMMMMMMMMy                                                yMMMMMMMMM   XX
" XX   MMMMMMMMMMy.                                            .yMMMMMMMMMM   XX
" XX   MMMMMMMMMMMMy.                                        .yMMMMMMMMMMMM   XX
" XX   MMMMMMMMMMMMMMy.                                    .yMMMMMMMMMMMMMM   XX
" XX   MMMMMMMMMMMMMMMMs.                                .sMMMMMMMMMMMMMMMM   XX
" XX   MMMMMMMMMMMMMMMMMMss.           ....           .ssMMMMMMMMMMMMMMMMMM   XX
" XX   MMMMMMMMMMMMMMMMMMMMNo         oNNNNo         oNMMMMMMMMMMMMMMMMMMMM   XX
" XX                                                                          XX
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

"     .o88o.                               o8o                .
"     888 `"                               `"'              .o8
"    o888oo   .oooo.o  .ooooo.   .ooooo.  oooo   .ooooo.  .o888oo oooo    ooo
"     888    d88(  "8 d88' `88b d88' `"Y8 `888  d88' `88b   888    `88.  .8'
"     888    `"Y88b.  888   888 888        888  888ooo888   888     `88..8'
"     888    o.  )88b 888   888 888   .o8  888  888    .o   888 .    `888'
"    o888o   8""888P' `Y8bod8P' `Y8bod8P' o888o `Y8bod8P'   "888"      d8'
"                                                                 .o...P'
"                                                                 `XER0'

set encoding=UTF-8

" - Vim Plug
call plug#begin('~/.vim/plugged')

Plug 'airblade/vim-gitgutter'
Plug 'ajh17/VimCompletesMe'
Plug 'christoomey/vim-tmux-navigator'
Plug 'dracula/vim', {'as': 'dracula'}
  
Plug 'itchyny/lightline.vim'
Plug 'itchyny/vim-gitbranch'

Plug 'jiangmiao/auto-pairs'
Plug 'justinmk/vim-dirvish'
Plug 'mattn/emmet-vim'
Plug 'mhinz/vim-startify'
Plug 'neovimhaskell/haskell-vim'
Plug 'pangloss/vim-javascript'
Plug 'ryanoasis/vim-devicons'

Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'

Plug 'w0rp/ale'

" - Initialize plugin system
call plug#end()

" - set leader key
let mapleader = ';'

" Indent Settings
set autoindent
set indentexpr=off
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2 

" Backup settings
set nowritebackup
set noswapfile
set nobackup


" - Basic setup
set nocompatible
syntax on
filetype plugin indent on

" - Finding files recursively
set path+=**

" Wild stuff and such
set wildmenu
set wildignore+=**/node_modules/**

" Mappings
" - map relative number toggle
nmap <silent> <C-l> :exec &rnu? "se rnu!" : "se rnu"<CR>

" - easy buffer navigation
noremap <leader>n :bn<cr>
noremap <leader>p :bp<cr>
noremap <leader>d :bd<cr>

" - easier window navigation
" map <leader>j <C-W>j<C-W>_
" map <leader>k <C-W>k<C-W>_
" map <leader>h <C-W>h<C-W>
" map <leader>l <C-W>l<C-W>

set winminheight=0
set winheight=999
" - set window height to 0 by default
" - helps with screen real-estate :)

" - editorconfigs
set number

" - for indent lines
" https://vi.stackexchange.com/questions/666/how-to-add-indentation-guides-lines
" set cursorcolumn
" set cursorline

set textwidth=80
set nohls
set noshowmatch
set noshowmode
setlocal spell spelllang=en_us
set nospell

set modeline
set nojoinspaces " pesky 2-spaces after the period thing - substack :p


" Plugin: dracula
" Recent Dracula Theme messed up a ton of things ...
" these settings resolve the issues 
let g:dracula_italic = 0
colorscheme dracula
highlight Normal ctermbg=None

" Plugin: GitGutter
set updatetime=1000
nmap <Leader>gs <Plug>GitGutterStageHunk
nmap <Leader>gu <Plug>GitGutterUndoHunk
nmap <Leader>gp <Plug>GitGutterPreviewHunk

" Plugin: Startify
let g:startify_custom_header =
        \ map(split(system('figlet zerodayz'), '\n'), '"   ". v:val')

let g:startify_files_number = 10

let g:startify_lists = [
      \ { 'type': 'files',     'header': [   'Recent Files']            },
      \ { 'type': 'bookmarks', 'header': [   'Bookmarks']      },
      \ { 'type': 'commands',  'header': [   'Commands']       },
      \ ]

" Plugin: Ale
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0


" Plugin: netrw {{{2
let g:loaded_netrwPlugin = 1
" let g:netrw_banner       = 0
" let g:netrw_bufsettings  = 'relativenumber'
" let g:netrw_keepdir      = 0
" let g:netrw_liststyle    = 1
" let g:netrw_sort_options = 'i'

" Plugin: lightline {{{1
set laststatus=2
let g:lightline = {
      \ 'colorscheme': 'Dracula',
      \ 'component': {
      \   'lineinfo': '%3l:%-2v',
      \ },
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ],
      \   'right': [ [ 'lineinfo' ],
      \              [ 'percent' ],
      \              [ 'fileencoding', 'filetype'] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'LightLineGitBranch',
      \   'filetype': 'MyFiletype',
      \   'fileformat': 'MyFileformat',
      \ }
    \ }

function! LightLineGitBranch()
  if exists("*gitbranch#name")
    let branch = gitbranch#name()
    return branch !=# '' ? ' '.branch : ''
  endif
  return ''
endfunction

function! MyFiletype()
  return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
endfunction

function! MyFileformat()
  return winwidth(0) > 70 ? (&fileformat . ' ' . WebDevIconsGetFileFormatSymbol()) : ''
endfunction

