#!/bin/sh
export DISPLAY=:0.0
bat_info=`acpi -b`

if echo $bat_info | grep Discharging > /dev/null 2>&1; then
  bat_level=`echo $bat_info | grep -P -o '[0-9]+(?=%)'`
  if [ `echo $bat_level` -le 6 ]; then
    notify-send --urgency critical 'Battery low!' "Battery level is $bat_level%!"
  fi
fi

exit 0
