#!/bin/bash

# Provisions docker env (only works with default machine for now)

if [ -x "$(command -v docker-machine)" > /dev/null ]
then
  # fetch the first running machine name
  isRunning=$(docker-machine ls | grep "Running")

  if [ -z "$isRunning" ];
  then
    docker-machine start # starts default machine
  fi
fi
