var $jscomp={scope:{},findInternal:function(f,b,l){f instanceof String&&(f=String(f));for(var n=f.length,k=0;k<n;k++){var u=f[k];if(b.call(l,u,k,f))return{i:k,v:u}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(f,b,l){if(l.get||l.set)throw new TypeError("ES3 does not support getters and setters.");f!=Array.prototype&&f!=Object.prototype&&(f[b]=l.value)};
$jscomp.getGlobal=function(f){return"undefined"!=typeof window&&window===f?f:"undefined"!=typeof global&&null!=global?global:f};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(f,b,l,n){if(b){l=$jscomp.global;f=f.split(".");for(n=0;n<f.length-1;n++){var k=f[n];k in l||(l[k]={});l=l[k]}f=f[f.length-1];n=l[f];b=b(n);b!=n&&null!=b&&$jscomp.defineProperty(l,f,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(f){return f?f:function(b,f){return $jscomp.findInternal(this,b,f).v}},"es6-impl","es3");
function _whatFont(){function f(){var a=b("<p>").css("font-family","S0m3F0n7"),c=b("<p>").css("font-family","serif"),d=b("<p>").css("font-family","sans-serif"),a=new p(new q(a)),c=new p(new q(c));new p(new q(d));v=a.isEqual(c)?"serif":"sans-serif"}var b,l,n,k,u,h,r,g,p,q,x,y,v,w=[];p=function(a,c,d){d=d||{};this.data=[];p.isSupported&&(this.typeInfo=a,this.text=c||"abcdefghijklmnopqrstuvwxyz",this.canvas_options=b.extend(this.canvas_options,d),this.canvas=b("<canvas>")[0],this.draw())};p.isSupported=
!!document.createElement("canvas").getContext;p.prototype={canvas_options:{fillStyle:"rgb(0,0,0)",height:50,size:"40px",textBaseline:"top",width:600},getFontOption:function(){return this.typeInfo.style+" "+this.typeInfo.weight+" "+this.canvas_options.size+" "+this.typeInfo.fonts},draw:function(){var a=this.canvas.getContext("2d");b.each(this.canvas_options,function(c,b){a[c]=b});a.font=this.getFontOption();a.fillText(this.text,0,0);return this.data=a.getImageData(0,0,this.canvas_options.width,this.canvas_options.height).data},
isEqual:function(a){var c=this.canvas_options.width*this.canvas_options.height*4,b=this.data,e=a.data;for(a=0;a<c;a+=1)if(b[a]!==e[a])return!1;return!0}};q=function(a){this.element=b(a);this.detect()};q.roundFloatWithPxUnit=function(a){a=Math.round(parseFloat(a));return isNaN(a)?"?":a+"px"};q.prototype={detect:function(){this.detectBasicCSS();this.variant=this.getVariant();this.stack=this.fonts.split(/,\s*/);this.testCanvas=new p(this);this.current=this.getCurrentFont()},detectBasicCSS:function(){this.fonts=
this.element.css("font-family");this.weight=this.element.css("font-weight");this.style=this.element.css("font-style");this.size=q.roundFloatWithPxUnit(this.element.css("font-size"));this.lineHeight=q.roundFloatWithPxUnit(this.element.css("line-height"));this.color=this.element.css("color")},getFullCSS:function(){var a=["font-family","font-weight","font-style"],c={},b;for(b=0;b<a.length;b++)c[a[b]]=this.element.css(a[b]);return c},getVariant:function(){return"normal"===this.weight&&"normal"===this.style?
"regular":"normal"===this.weight?this.style:"normal"===this.style?this.weight:this.weight+" "+this.style},getCurrentFont:function(){var a=this.stack.slice(0),c,d,e;for(c=0;c<this.stack.length;c++)if(d=b.extend({},this,{fonts:a[c]+" ,serif",stack:[a[c],"serif"]}),e=b.extend({},this,{fonts:a[c]+", sans-serif",stack:[a[c],"sans-serif"]}),d=new p(d),e=new p(e),d.isEqual(e)&&this.testCanvas.isEqual(d))return a[c];return v&&(c=b.extend({},this,{fonts:v,stack:[v]}),c=new p(c),this.testCanvas.isEqual(c))?
v:a[0]},saveDesignToServer:function(a){var c=this;b.getJSON(n+"/designs/create?callback=?",{font:this.current,style:this.style,weight:this.weight,image_base64:this.screenshot,url:document.location.toString()},function(b){b.url&&(c.designURL=b.url);a&&a()})}};k={STYLE_PRE:"__whatfont_",CSS_URL:"https://chengyinliu.com/wf.css?ver=2.1",init:function(){k.CSS_URL&&(k.$el=b("<link>").attr({rel:"stylesheet",href:k.CSS_URL}).appendTo("head"))},restore:function(){k.$el&&k.$el.remove()},getClassName:function(a){a=
"string"===typeof a?[a]:a;return k.STYLE_PRE+a.join(" "+k.STYLE_PRE)}};g={getSlugWithCSSName:{},fontData:{},services:{},init:function(){g.typekit();g.google();g.fontdeck()},typekit:function(){var a;b("script").each(function(b){if(b=this.src.match(/use\.typekit\.(com|net)\/(.+)\.js/))return a=b[2],!1});a&&b.getJSON("https://typekit.com/api/v1/json/kits/"+a+"/published?callback=?",function(a){a.errors||(g.services.typekit=a.kit,b.each(a.kit.families,function(a,c){b.each(c.css_names,function(a,b){g.getSlugWithCSSName[b.toLowerCase()]=
c.slug});g.fontData[c.slug]=g.fontData[c.slug]||{name:c.name,services:{}};g.fontData[c.slug].services.Typekit={id:c.id,url:"http://typekit.com/fonts/"+c.slug}}))})},google:function(){b("link").each(function(a,c){var d=b(c).attr("href");0<=d.indexOf("fonts.googleapis.com/css?")&&(d=d.match(/\?family=([^&]*)/)[1].split("|"),b.each(d,function(a,b){var c=b.split(":")[0],d=c.replace(/\+/g," "),e=d.replace(/ /g,"-").toLowerCase();g.getSlugWithCSSName[d]=e;g.fontData[e]=g.fontData[e]||{name:d,services:{}};
g.fontData[e].services.Google={url:"http://www.google.com/webfonts/family?family="+c}}))})},fontdeck:function(){var a=[],c=location.hostname;b("link").each(function(c,e){var d=b(e).attr("href");0<=d.indexOf("fontdeck.com")&&(d=d.match(/^.*\/(\d+)\.css$/))&&a.push(d[1])});b("script").each(function(c,e){var d=b(e).attr("src");"undefined"!==typeof d&&0<=d.indexOf("fontdeck.com")&&(d=d.match(/^.*\/(\d+)\.js$/))&&a.push(d[1])});b.each(a,function(a,e){b.getJSON("http://fontdeck.com/api/v1/project-info?project="+
e+"&domain="+c+"&callback=?",function(a){"undefined"!==typeof a&&"undefined"!==typeof a.provides&&b.each(a.provides,function(a,b){var c=b.name,d=c.replace(/ /g,"-").toLowerCase(),e=c.split(" ")[0],e=b.url||"http://fontdeck.com/search?q="+e;g.getSlugWithCSSName[c]=d;g.fontData[d]=g.fontData[d]||{name:c,services:{}};g.fontData[d].services.Fontdeck={url:e}})})})},getFontDataByCSSName:function(a){a=a.replace(/^"|'/,"").replace(/"|'$/,"");return(a=g.getSlugWithCSSName[a])&&g.fontData[a]?g.fontData[a]:
null},getFontNameByCSSName:function(a){a=a.replace(/^"|'/,"").replace(/"|'$/,"");return(a=g.getSlugWithCSSName[a])&&g.fontData[a]?g.fontData[a].name:null}};x=function(){this.currentCacheId=-1;this.el=b.wfElem("div",["tip","elem"],"");this.$el=b(this.el);this.init()};x.prototype={init:function(){var a=this;this.$el.appendTo("body");b("body :visible").on("mousemove.wf",function(c){a.update(b(this),c);a.show();c.stopPropagation()});b("body").on("mouseout.wf",function(b){a.hide()})},hide:function(){this.$el.hide()},
show:function(){this.$el.show()},update:function(a,b){var c=a.data("wfCacheId");this.updatePosition(b.pageY,b.pageX);this.element!==a&&(c||(c=w.length,w.push(void 0)),this.element=a,this.element.data("wfCacheId",c),w[c]=this.typeInfo=w[c]||new q(a),this.updateText(this.typeInfo.current))},updatePosition:function(a,b){this.$el.css({top:a+12,left:b+12})},updateText:function(a){this.$el.text(a).css("display","inline-block")},remove:function(){this.$el.remove();b("body :visible").off("mousemove.wf");
b("body").off("mouseout.wf")}};h={fontServiceIcons:{},init_tmpl:function(){h.tmpl=function(){var a=b('<div class="elem panel"><div class="panel_title"><span class="title_text"></span><a class="close_button" title="Close">&times;</a></div><div class="panel_content"><ul class="panel_properties"><li><dl class="font_family"><dt class="panel_label">Family</dt><dd class="panel_value"></dd></dl></li><li><div class="style_weight"><dl class="font_style"><dt class="panel_label">Style</dt><dd class="panel_value"></dd></dl><dl class="font_weight"><dt class="panel_label">Weight</dt><dd class="panel_value"></dd></dl><dl></dl></div></li><li><div class="size_line_height_color"><dl class="size section"><dt class="panel_label">Size</dt><dd class="panel_value"></dd></dl><dl class="line_height"><dt class="panel_label">Line Height</dt><dd class="panel_value"></dd></dl><dl class="color"><div class="color_info"><dt class="panel_label">Color</dt><dd class="panel_value"><a title="Click to change color format" class="color_info_sample">&nbsp;</a><span class="color_info_value"></span></dd></dl></div></li><li class="panel_no_border_bottom"><dl class="type_info clearfix"><dt class="panel_label"></dt><dd class="type_preview">AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz</dd></dl></li></ul><div class="panel_tools clearfix"><div class="panel_tools_left"><div class="font_services" style="display:none;">Via </div></div><div class="panel_tools_right"><a href="https://twitter.com/share" class="tweet_icon" target="_blank">&nbsp;</a></div></div></div></div>');
return function(){return a.clone()}}()},init:function(){b("body :visible").on("click.wf",h.pin);h.init_tmpl();h.panels=b([]);h.fontServiceIcons.Typekit=b("<span>").addClass("service_icon service_icon_typekit").text("Typekit");h.fontServiceIcons.Google=b("<span>").addClass("service_icon service_icon_google").text("Google Web Fonts");h.fontServiceIcons.Fontdeck=b("<span>").addClass("service_icon service_icon_fontdeck").text("Fontdeck")},restore:function(){b("body :visible").unbind("click.wf",h.pin);
h.panels.remove()},convertClassName:function(a){a.find("*").add(a).each(function(a,d){var c=b(d).attr("class");if(c=""===c?"basic":c+" basic")c=c.split(" "),b(d).attr("class",k.getClassName(c))});return a},typePreview:function(a,c){b(c).find(".type_preview").css(a.getFullCSS());return c},fontService:function(a,c){var d=g.getFontDataByCSSName(a.current),e;e=b("<ul>").addClass("font_service");d?(b.each(d.services,function(a,c){b("<li>").append(b("<a>").append(b(h.fontServiceIcons[a]).clone()).attr("href",
c.url).attr("target","_blank")).appendTo(e)}),b(c).find(".font_services").append(e).show()):b(c).find(".font_services").hide();return c},fontFam:function(a,c){var d=a.fonts.replace(/;/,"").split(/,\s*/),e=a.current,f=!1,t;a.fonts.replace(/;/,"").split(/,\s*/);for(t=0;t<d.length;t+=1)if(d[t]!==e)d[t]="<span class='fniu'>"+d[t]+"</span>";else{d[t]="<span class='fiu'>"+d[t]+"</span>";f=!0;break}d=d.join(", ")+";";f||(d+=" <span class='.fiu'>"+e+"</span>");d="<div class="+k.getClassName("fontfamily_list")+
">"+d+"</div>";b(c).find(".font_family>dd").html(d);return c},fontWeight:function(a,b){var c=a.weight;b.find(".font_weight>dd").text(c)},fontStyle:function(a,b){var c=a.style;b.find(".font_style>dd").text(c)},sizeLineHeight:function(a,c){var d=a.size,e=a.lineHeight;b(c).find(".size>dd").text(d);b(c).find(".line_height>dd").text(e);return c},color:function(a,c){function d(a,b){a.css("visibility","hidden");a.css("font-size","");a.text("1");var c=a.height(),d=parseInt(a.css("font-size"),10);for(a.text(b);a.height()>
c&&0<=d;)d--,a.css("font-size",d+"px");0===d&&a.css("font-size","");a.css("visibility","")}var e=a.color,f=b(c).find(".color_info_sample"),k=b(c).find(".color_info_value"),h,g,l;-1!==e.indexOf("rgba")?(f.hide(),setTimeout(function(){d(k,e)},0)):(h=e.match(/^rgb\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*\)$/),g=parseInt(h[1],10).toString(16),l=parseInt(h[2],10).toString(16),h=parseInt(h[3],10).toString(16),g=1===g.length?"0"+g:g,l=1===l.length?"0"+l:l,h=1===h.length?"0"+h:h,g=[e,"#"+g+l+h],f.css("background-color",
e).click(function(a,b,c){return function(e){b=(b+1)%a.length;d(c,a[b]);e.preventDefault();return!1}}(g,0,k)).click())},tweet:function(a,c){var d=b(c).find(".tweet_icon"),e=a.current,f=g.getFontNameByCSSName(e)||e;d.click(function(){var b=d.attr("href");h.takeScreenshot(c.e,c,function(){b+="?text="+encodeURIComponent("Check this design out with "+f+".")+"&url="+encodeURIComponent(a.designURL||window.location.href)+"&via=What_Font";window.open(b,"","height=430,width=550")});return!1})},panelContent:function(a,
c){b("typePreview fontService fontFam fontWeight fontStyle sizeLineHeight color tweet".split(" ")).each(function(b,e){h[e](a,c)})},panelTitle:function(a,c){var d=a.current,d=(g.getFontNameByCSSName(d)||d)+" - "+a.variant;b(c).find(".title_text").html(d);(function(a){b(a).find(".close_button").click(function(c){b(a).remove();c.stopPropagation();return!1})})(c);return c},get:function(a){var c=h.tmpl();a=new q(a);h.panelTitle(a,c);h.panelContent(a,c);h.convertClassName(c);c.typeInfo=a;b(c).click(function(a){b("html > .__whatfont_panel").last()[0]!==
c[0]&&(b(this).find("*").css("-webkit-animation","none"),b(this).detach(),b(this).appendTo("html"))});return c},takeScreenshot:function(a,b,d){b.typeInfo.designURL?d(a,b):m.takeScreenshotAroundPoint(function(c){c?(b.screenshot=c,b.typeInfo.screenshot=c,b.typeInfo.saveDesignToServer(function(){d(a,b)})):d(a,b)},a.pageX,a.pageY,480,320)},showPanel:function(a,c){b(c).css({top:a.pageY+12,left:a.pageX-13}).appendTo("html");h.panels=h.panels.add(c)},pin:function(a){var b;y.hide();b=h.get(this);b.e=a;h.showPanel(a,
b);a.stopPropagation();a.preventDefault()},hideAll:function(){b(h.panels).hide()},showAll:function(){b(h.panels).find("*").css("-webkit-animation","none");b(h.panels).show()}};u={TOOLBAR:null,init:function(){var a=b.wfElem("div","exit","Exit WhatFont");b.wfElem("div","help","<strong>Hover</strong> to identify<br /><strong>Click</strong> to pin a detail panel");u.TOOLBAR=b("<div>").addClass(k.getClassName(["elem","control"])).append(a).appendTo("body");b(a).click(function(){r.restore()})},restore:function(){b(u.TOOLBAR).remove()}};
r={shortcut:function(a){27===(a.keyCode||a.which)&&(r.restore(),a.stopPropagation())},restore:function(a){b("body :visible").unbind("mousemove",r.updateTip);b("body :visible").unbind("click",r.pinPanel);u.restore();y.remove();h.restore();k.restore();b("body").unbind("keydown",r.shortcut);b(window).unbind("resize.whatfont");window._WHATFONT=!1},init:function(a){a=a||{};!b&&jQuery&&(b=jQuery);if("undefined"!==typeof window._WHATFONT&&window._WHATFONT||!b)return!1;window._WHATFONT=!0;b.wfElem=function(a,
d,e,f){var c=b("<"+a+">");d=d||[];e=e||"";d="string"===typeof d?[d]:d;d.push("basic");c.addClass(k.getClassName(d));"string"===typeof e?c.html(e):e.constructor===Array?b.map(e,function(a,b){return c.append(a)}):c.append(e);"undefined"!==typeof f&&c.attr(f);return c[0]};f();a.isDisablingUI||(k.init(),y=new x,h.init(),u.init(),b("body").keydown(r.shortcut));g.init();m.fullScreenshot=null;b(window).bind("resize.whatfont",function(){m.fullScreenshot=null})}};var m={captureAll:!0,format:"image/jpeg",quality:.7,
capturer:function(a,c){c=c||{};var d,e;d=b(window).scrollTop();e=b(window).scrollLeft();if(p.isSupported&&l)try{b(window).scrollTop(0),b(window).scrollLeft(0),l([document.body],{onrendered:function(f){b(window).scrollTop(d);b(window).scrollLeft(e);m.fullScreenshot=f;a(f.toDataURL(c.format||m.format,c.quality||m.quality))},proxy:void 0})}catch(z){b(window).scrollTop(d),b(window).scrollLeft(e),a()}else a(),b(window).scrollTop(d),b(window).scrollLeft(e)},dataURLToCanvas:function(a,c){try{var d=b("<canvas>")[0],
e=d.getContext("2d"),f=new Image;f.onload=function(){e.height=f.height;e.width=f.width;e.drawImage(f,0,0);c(d)};f.src=a}catch(t){c(null)}},takeFullScreenshot:function(a){if(m.fullScreenshot)return a(m.fullScreenshot);m.capturer(function(b){m.fullScreenshot=b;a(b)},{quality:m.quality,format:m.format})},takePartialScreenshot:function(a){h.hideAll();window.setTimeout(function(){m.capturer(function(b){h.showAll();a(b)})},0)},takeCroppedScreenshot:function(a,c,d,e,f,h){var g,k,l;g=m.captureAll?m.takeFullScreenshot:
m.takePartialScreenshot;void 0!==c&&(k=e-c,l=f-d);h=h||{};g(function(e){var f;if(!e)return a();void 0===c?a(e):(f=new Image,f.src=e,f.onload=function(){var e,g;e=b("<canvas>")[0];e.width=k;e.height=l;g=e.getContext("2d");g.fillStyle="rgba(255,255,255,1)";g.fillRect(0,0,k,l);g.drawImage(f,c,d,k,l,0,0,k,l);e=e.toDataURL(h.format||m.format,h.quality||m.quality);a(e)});return!0},h)},takeScreenshotAroundPoint:function(a,c,d,e,f,h){c-=e/2;e=c+e;d-=f/2;f=d+f;var g,k;m.captureAll||(g=b(window).scrollTop(),
k=b(window).scrollLeft(),c-=k,e-=k,d-=g,f-=g);0>c&&(e-=c,c=0);0>d&&(f-=d,d=0);m.takeCroppedScreenshot(a,c,d,e,f,h)}};return{setJQuery:function(a){b=a},setHTML2Canvas:function(a){l=a},setScreenshot:function(a){m=b.extend(m,a)},setAPIURL:function(a){n=a},setCSSURL:function(a){k.CSS_URL=a},getVer:function(){return"2.1"},init:r.init,restore:r.restore,getTypeInfoForSelectedText:function(){if(!window||!window.getSelection)return null;var a=window.getSelection();return 0===a.toString().length?null:new q(a.anchorNode.parentElement)},
getFontServiceInfo:function(a){return g.getFontDataByCSSName(a.current)}}}
(function(){function f(){if("undefined"!==typeof _WHATFONT&&_WHATFONT)return b.restore(),!1;wf$.getJSON=function(b,f,k){k||(k=f,f=void 0);chrome.extension.sendRequest({action:"getJSON",url:b,data:f},k)};b.setJQuery(wf$);b.setCSSURL(chrome.extension.getURL("wf.css"));b.setAPIURL("http://www.whatfonttool.com/api/v1");b.setScreenshot({capturer:function(b,f){chrome.extension.sendRequest({action:"capture",options:f||{format:"image/png"}},b)},captureAll:!1,format:"image/jpeg",quality:.9});b.init();return!0}
var b=b||_whatFont();chrome.extension.onRequest.addListener(function(b,n,k){"initOrRestore"===b.action&&k(f())});chrome.extension.sendRequest({action:"onload"})})();
